config/routes.rb
Rails.application.routes.draw do
get "/peppers" => redirect("/")
get "/users" => redirect("/")
  devise_for :users
  resources :users
  resources :peppers do
    resources :tasks
  end
  resources :main

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pepper.rb
class Pepper < ApplicationRecord
  belongs_to :user #dependants destroy
  has_many :tasks
  def self.types_and_labels
    [['Progress', "Progress"],['Mean value', "Mean"], ['Tasks', "ToDo"]]
  end

end

class Progress < Pepper
end

class Trend < Pepper
end

class ToDo < Pepper

end

class Mean < Pepper
end

class Negative < Pepper
end

class Piece < Pepper
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :pepper
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :peppers

  has_attached_file :picture, :default_url => "penguin_normal.jpg"
  validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:firstName, :lastName, :email, :picture])
      devise_parameter_sanitizer.permit(:account_update, keys: [:firstName, :lastName, :email, :picture])
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @peppers=Pepper.where(user_id:"@user.id")
  end
end

app/controllers/peppers_controller.rb
class PeppersController < ApplicationController
  before_action :set_pepper, only: [:show, :edit, :update, :destroy]

  # GET /peppers
  # GET /peppers.json
  def index
    @peppers = Pepper.all
    @user = User.find(current_user.id)
  end

  # GET /peppers/1
  # GET /peppers/1.json
  def show
    @user = User.find(current_user.id)
    @peppers=@user.peppers
    @pepper = Pepper.find(params[:id])
    @tasks = @pepper.tasks
  end

  # GET /peppers/new
  def new
    @pepper = Pepper.new
    @user = User.find(current_user.id)
    @peppers=@user.peppers
  end

  # GET /peppers/1/edit
  def edit
    @user = User.find(current_user.id)
    @peppers=@user.peppers
    @pepper = Pepper.find(params[:id])
  end

  # POST /peppers
  # POST /peppers.json
  def create
    @pepper=Pepper.new(pepper_params)
    @pepper.user_id=current_user.id
    @pepper.done=false
    @pepper.currVal=0


    respond_to do |format|
      if @pepper.save
        format.html { redirect_to pepper_path(@pepper), notice: 'Pepper was successfully created.' }
        format.json { render :show, status: :created, location: @pepper }
      else
        format.html { render :new }
        format.json { render json: @pepper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peppers/1
  # PATCH/PUT /peppers/1.json
  def update
    respond_to do |format|
      if @pepper.update(pepper_params)
        format.html { redirect_to @pepper, notice: 'Pepper was successfully updated.'}
        format.json { render json: @pepper, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @pepper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peppers/1
  # DELETE /peppers/1.json
  def destroy
    @pepper.destroy
    respond_to do |format|
      format.html { redirect_to peppers_url, notice: 'Pepper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pepper
      @pepper = Pepper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pepper_params
      params.require(:pepper).permit(:user_id, :name, :deadline, :units, :goal, :type, :positive, :currVal)
    end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_pepper
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.pepper_id=@pepper.id
    @task.status=false
    respond_to do |format|
      if @task.save
        format.html { redirect_to pepper_path(@pepper), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render json: @task, status: :ok}
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :status)
    end

    def set_pepper
      @pepper = Pepper.find(params[:pepper_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.find(current_user.id)
  end

  def show
      @user = User.find(params[:id])
      @peppers=Pepper.where(user_id:"@user.id")
  end

  def edit
  end

  def destroy
    @user = User.find(current_user.id)

    if @user.destroy
        redirect_to root_url, notice: "User deleted."
      else
        redirect_to root_url, notice: "User NOT deleted."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%= yield(:title) %></title>
      <%= csrf_meta_tags %> 
      <!-- <meta name="referrer" content="no-referrer"> -->
      <!-- Hat bei mir immer einen Fehler ("ActionController::InvalidAuthenticityToken") geworfen.
      Konnte mich somit nicht anmelden oder einen Pepper generieren -Marion -->
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Meddon" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
  </head>
  <body>
  <% if user_signed_in? %>
  <div class="main_box">
    <div class="side-bar">
      <div class="profile-pic-main">
        <%= link_to image_tag(@user.picture, {class: 'img-main'}), edit_user_registration_path %>
      </div>
      <br>
      <h3>Hello <%= current_user.firstName %>!</h3>
      <%= button_to '+ New tracker', new_pepper_path, :method => :get, :class => 'btn' %>
      <h4><%= link_to 'Overview', root_path %></h4>
      <div class="overview-list-peppers">
        <% if @user.peppers.empty? %>
        <p class="info-no-peppers">(You dont have any peppers yet.)</p>
      <% else %>
        <% @user.peppers.each do |pepper| %>
          <h6><%= link_to(pepper.name.to_s, pepper_path(pepper)) %></h6>
        <% end %>
      <% end %>
      </div>
      <% if user_signed_in? %>
        <%= button_to 'Log out', destroy_user_session_path, method: :delete, :class => 'btn btn-danger btn-sm' %>
      <% else %>
        <%= link_to 'Log In', new_user_session_path %>
        <%= link_to 'Sign Up', new_user_registration_path %>
      <% end %>

      <p>
        <a class="button" data-turbolinks="false" href="#popup2"><%= image_tag "penguin-help.jpg", class: 'helper' %></a>
      </p>
      <div id="popup2" class="overlay light">
        <div class="popup">
          <a class="close" data-turbolinks="false" href="#">&times;</a>

          <h4>Need some Help?</h4>
          <div class="help_content">
            These are the current available trackers:
            <ul class="overflow">
              <li>Progress bar<span></span></li>
              <li>Mean value<span></span></li>
              <li>Tasks<span></span></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <%= yield %>
  </div>
  <% else %>
    <%= yield %>
    <% end -%>
  </body>
</html>

app/views/main/index.html.erb
<% content_for :title, "Tracker" %>

  <div class="content">
    <h1 class="display-title">Peppers</h1>
    <% if @user.peppers.empty? %>
        <%= link_to image_tag("penguin-sad.png", {class: 'img-sad'}) %>
        <h5 class="info-no-peppers">No peppers available!</h5>
    <% else %>
      <div class="container-trackers">
        <% @user.peppers.each do |pepper| %>
          <% if pepper.class.name === "ToDo" %>
            <%= link_to pepper_path(pepper) do %>
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><%= pepper.name %></h5>
                  <h6 class="card-subtitle mb-2 text-muted">Task List</h6>
                  <p class="card-text">Number of tasks: <%= pepper.tasks.length %></p>
                </div>
              </div>
            <% end -%>
          <% else %>
            <%= link_to pepper_path(pepper) do %>
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><%= pepper.name %></h5>
                  <h6 class="card-subtitle mb-2 text-muted">Goal: <%= pepper.goal %>  <%= pepper.units %></h6>
                  <p class="card-text">Current value: <%= pepper.currVal %> <%= pepper.units %></p>
                </div>
              </div>
            <% end -%>
          <% end -%>
        <% end -%>
      </div>
    <% end -%>
  </div>

app/views/peppers/_form.html.erb
<%= form_with(model: pepper, local: true) do |f| %>
  <% if pepper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pepper.errors.count, "error") %> prohibited this pepper from being saved:</h2>

      <ul>
      <% pepper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="create_form">
    <div class="field form-group">
      <%= f.label :name_your_pepper %>
      <%= f.text_field :name, placeholder: 'Name', :class => 'form-control', :required => true%>

      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text" for="inputGroupSelect01">Pepper type</label>
        </div>
        <%= f.select(:type, options_for_select(Pepper.types_and_labels), {}, { :class => 'custom-select', :id => 'inputGroupSelect01'}) %>
      </div>

      <div class="wrapper-no-tasks">
        <%= f.label :What_do_you_need?, 'What do you want to track? (e.g. steps, words, ...)'%>
        <%= f.text_field :units, placeholder: "Units", :class => 'form-control'%>

        <%= f.label :goal, 'Goal (enter a number)' %>
        <%= f.number_field :goal, placeholder: "Goal", :class => 'form-control', :min => 1%>

        <div class="radio-wrapper">
          <div class="radio-pepper">
            <%= f.radio_button :positive, true, :value => true, :name => 'radio1', :id => 'radio1'%>
            <%= label :positive, "at least" %>
          
            <%= f.radio_button :positive, false, :value => false, :name => 'radio1', :id => 'radio2'%>
            <%= label :positive, "less than"%>
          </div>
        </div>
      </div>

      <%= f.label :deadline %>
      <%= f.date_field :deadline, :class => 'form-control date-picker' %>
    </div>

    <%= f.submit "Save pepper", :class => 'btn btn-primary btn-lg'%>
  </div>
  <script>
    $('.custom-select').change(function() {
      if($('.custom-select').val() === 'Mean') {
        $('.radio-wrapper').show();
      } else {
        $('.radio-wrapper').hide();
      }
      if($('.custom-select').val() === 'ToDo') {
        $('.wrapper-no-tasks').hide();
      } else {
        $('.wrapper-no-tasks').show();
      }
    });
  </script>
<% end %>

app/views/peppers/edit.html.erb
<% content_for :title, "Edit Pepper" %>
<div class="main_box">
  <div class="left_main">
    <div class="pos">
      <div class="profile_pic_main">
        <%= link_to image_tag("https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=26f427f929772c4a2bb1da62b3edca86&dpr=1&auto=format&fit=crop&w=1000&q=80&cs=tinysrgb", {class: 'img_main'}), edit_user_registration_path %>
      </div>
      <h3 class="hello">Hello <%= current_user.firstName %></h3>
      <div class="make_btn"><%= link_to 'New Tracker', new_pepper_path, :class => 'overview_title_a' %></div>
      <h2 class="overview_title"><%= link_to 'Overview', root_path %></h2>
      <div class="overview">
      </div>
    </div>
  </div>
  <div class="right_edit">
    <h2 class="title_edit">Edit <%=@pepper.name%></h2>


    <%= link_to 'Back', pepper_path(@pepper) %>
  </div>
</div>

app/views/peppers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peppers</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>ID</th>
      <th>User</th>
      <th>Units</th>
      <th>Goal</th>
      <th>Deadline</th>
      <th>Done?</th>
      <th>Current Value</th>
      <th>Type</th>
      <th>Positive?</th>
    </tr>
  </thead>

  <tbody>
    <% @peppers.each do |pepper| %>
      <tr>
        <td><%= pepper.name %></td>
        <td><%= pepper.id %></td>
        <td><%= pepper.user_id %></td>
        <td><%= pepper.units %></td>
        <td><%= pepper.goal %></td>
        <td><%= pepper.deadline %></td>
        <td><%= pepper.done %></td>
        <td><%= pepper.currVal %></td>
        <td><%= pepper.type %></td>
        <td><%= pepper.positive %></td>
        <td><%= link_to 'Show', pepper_path(pepper) %></td>
        <td><%= link_to 'Edit', edit_pepper_path(pepper) %></td>
        <td><%= link_to 'Destroy', pepper_path(pepper), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', root_path %>

app/views/peppers/new.html.erb
<% content_for :title, "New Pepper" %>
  <div class="content">
      <h2>Create pepper</h2>
      <div class="form-edit-tracker">
        <%= render 'form', pepper: @pepper %>
      </div>
  </div>
  

app/views/peppers/show.html.erb
<% content_for :title, "Peppers" %>
  <div class="content">
    <h1><%= @pepper.name%></h1>
    <% if @pepper.class.name === "ToDo" %>
      <%= content_tag :div, class: "container-tracker", data: {info: @pepper.to_json, tasks: @pepper.tasks.to_json} do %>
      <% end %>
    <% else %>
      <%= content_tag :div, class: "container-tracker", data: {info: @pepper.to_json} do %>
      <% end %>
    <% end %>

    <button class="btn btn-primary" data-toggle="modal" data-target="#myModal">
      Delete this pepper
    </button>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Delete Pepper</h4>
          </div>
          <div class="modal-body">
            Do you really want to delete this pepper (<%= @pepper.name %>)?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Close</button>
            <%= button_to 'Delete this pepper', pepper_path(@pepper), method: :delete, :class => 'btn btn-danger btn-simple' %>
          </div>
        </div>
      </div>
    </div>

    <script>
        $('.container-tracker').empty();
        var data = $(".container-tracker").data("info");
        var tasks = $(".container-tracker").data("tasks");
        if(tasks === undefined) {
          $(document).on('turbolinks:load', () => {
              setTracker("<%= @pepper.class.name %>", data);
          });
        } else {
          $(document).on('turbolinks:load', () => {
              setTracker("<%= @pepper.class.name %>", data, tasks);
          });
        }
    </script>
  </div>

app/views/tasks/_form.html.erb
<%= form_for [@pepper.becomes(Pepper), @task]  do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Peppers</th>
      <th>Name</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.peppers %></td>
        <td><%= task.name %></td>
        <td><%= task.status %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_pepper_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Peppers:</strong>
  <%= @task.peppers %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/index.html.erb
<% content_for :title, "Tracker" %>
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.firstName %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Profile', edit_user_registration_path %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_registration_path %></td>
    <td><%= link_to 'Delete', user, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New User', new_user_registration_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to (new_session_path(resource_name)) do %>
    <div class="signup"><p>Log In</p>
    </div>
  <% end -%>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to (new_registration_path(resource_name)) do %>
    <div class="signup"><p>Sign Up</p>
    </div>
  <% end -%>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to(new_password_path(resource_name), :class => "forgot") do %>
    <div class="forgot">
      <p>Forgot Password?</p>
    </div>
  <% end -%>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<% if current_user %>

<h1>User</h1>
<%= @user.id %>
<%= @user.firstName %>
<%= @user.lastName %>
<%= image_tag @user.picture.url %>

<h1>Peppers</h1>
<table border="1">
    <thead>
<tr>
  <th>Name</th>
  <th>User</th>
    <th>Deadline</th>
</tr>
</thead>
<% @user.peppers.each do |pepper| %>
<tr>
  <td><%= pepper.name %></td>
  <td><%= pepper.id %></td>
    <td><%= pepper.deadline %></td>
  <td><%= link_to 'Show', pepper_path(pepper) %></td>
  <td><%= link_to 'Edit', edit_pepper_path(pepper) %></td>
  <td><%= link_to 'Destroy', pepper_path(pepper), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
  <% end %>
  </table>
  <%= link_to 'New Pepper', new_pepper_path %>
<%= link_to 'Edit', edit_user_registration_path(@user) %> |
<%= link_to 'Back', users_path %>

<p id="notice"><%= notice %></p>
<%end%>